### ISSUE TITLE
Not compatible with vanilla tweeks more mob heads

### ISSUE THREAD

**Issue by andreas-hub** [Jerrycyx/Warden-With-Loot#1]
If I install the [vanilla tweeks](https://vanillatweaks.net/picker/datapacks) datapack `More Mob Heads` this datapack doesn't work at all. I've tried a lot of other vanilla tweeks datapacks but the issue was only with `More Mob Heads`.

I don't know if the issue is from this datapack or from `More Mob Heads` but the latter seems to work fine either way.

**Comment by Jerrycyx** [comment]
`More Mob Heads` and `Warden with Loot` both work by overriding the vanilla loot table, so based on the current running mode of this mod, I cannot make them compatible.
﻿
Please try deleting the `data/minecraft/loot_table/entities/warden.json` in the `.JAR` file of `More Mob Heads` to disable its loot table modifications related to warden. This may make it compatible with this mod.
